export const Rooms = [
    {
        id: 1,
        name: "Single economy",
        slug: "single-economy",
        type: "single",
        price: 1000,
        size: 200,
        capacity: 1,
        pets: false,
        breakfast: false,
        featured: false,
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id: 2,
        name: "Single basic",
        slug: "single-basic",
        type: "single",
        price: 1500,
        size: 250,
        capacity: 1,
        pets: false,
        breakfast: false,
        featured: false,
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/833045/pexels-photo-833045.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id: 3,
        name: "Single standard",
        slug: "single-standard",
        type: "single",
        price: 2500,
        size: 300,
        capacity: 1,
        pets: true,
        breakfast: false,
        featured: false,
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/3201763/pexels-photo-3201763.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id:4,
        name: "Single deluxe",
        slug: "single-deluxe",
        type: "single",
        price: 3000,
        size: 400,
        capacity: 1,
        pets: true,
        breakfast: true,
        featured: false,
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/9298/light-art-house-architecture.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id:5,
        name: "Double economy",
        slug: "double-economy",
        type: "double",
        price: 2000,
        size: 300,
        capacity: 2,
        pets: false,
        breakfast: false,
        featured: false,
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/26139/pexels-photo-26139.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id:6,
        name: "Double deluxe",
        slug: "double-deluxe",
        type: "double",
        price: 4000,
        size: 500,
        capacity: 2,
        pets: true,
        breakfast: true,
        featured: true,
        intro:"Give yourself you deserve",
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id:7,
        name: "Family deluxe",
        slug: "family-deluxe",
        type: "family",
        price: 5000,
        size: 700,
        capacity: 6,
        pets: false,
        breakfast: true,
        featured: true,
        intro: "Made specially for family. Enjoy your holydays as never before",
        extras: [
            "Plush pillows and breathable bed linens",
            "Soft, oversized bath towels",
            "Full-sized, pH-balanced toiletries",
            "Complimentary refreshments",
            "Adequate safety/security",
            "Internet",
            "Comfortable beds"
          ],
        images: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"  
    },
    {
        id: 8,
        name: "Presidential",
      slug: "presidential-room",
      type: "presidential",
      price: 6000,
      size: 1000,
      capacity: 10,
      pets: true,
      breakfast: true,
      featured: true,
      intro: "Feel like a king in your kingdom",
      extras: [
        "Plush pillows and breathable bed linens",
        "Soft, oversized bath towels",
        "Full-sized, pH-balanced toiletries",
        "Complimentary refreshments",
        "Adequate safety/security",
        "Internet",
        "Comfortable beds"
      ],
      images: "https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    {
      id: 9,
      name: "Double basic",
      slug: "double-basic",
      type: "double",
      price: 2500,
      size: 350,
      capacity: 2,
      pets: false,
      breakfast: false,
      featured: false,
      extras: [
        "Plush pillows and breathable bed linens",
        "Soft, oversized bath towels",
        "Full-sized, pH-balanced toiletries",
        "Complimentary refreshments",
        "Adequate safety/security",
        "Internet",
        "Comfortable beds"
      ],
      images: "https://images.pexels.com/photos/4217/hotel-bed-bedroom-room.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    {
      id: 10,
      name: "Double standard",
      slug: "double-standard",
      type: "double",
      price: 3000,
      size: 400,
      capacity: 2,
      pets: true,
      breakfast: false,
      featured: false,
      extras: [
        "Plush pillows and breathable bed linens",
        "Soft, oversized bath towels",
        "Full-sized, pH-balanced toiletries",
        "Complimentary refreshments",
        "Adequate safety/security",
        "Internet",
        "Comfortable beds"
      ],
      images:"https://images.pexels.com/photos/97083/pexels-photo-97083.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    {
      id: 11,
      name: "Family economy",
      slug: "family-economy",
      type: "family",
      price: 3000,
      size: 500,
      capacity: 3,
      pets: false,
      breakfast: false,
      featured: false,
      extras: [
        "Plush pillows and breathable bed linens",
        "Soft, oversized bath towels",
        "Full-sized, pH-balanced toiletries",
        "Complimentary refreshments",
        "Adequate safety/security",
        "Internet",
        "Comfortable beds"
      ],
      images: "https://images.pexels.com/photos/172872/pexels-photo-172872.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    {
      id: 12,
      name: "Family basic",
      slug: "family-basic",
      type: "family",
      price: 3500,
      size: 550,
      capacity: 4,
      pets: false,
      breakfast: false,
      featured: false,
      extras: [
        "Plush pillows and breathable bed linens",
        "Soft, oversized bath towels",
        "Full-sized, pH-balanced toiletries",
        "Complimentary refreshments",
        "Adequate safety/security",
        "Internet",
        "Comfortable beds"
      ],
      images: "https://images.pexels.com/photos/1579253/pexels-photo-1579253.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    {
      id: 13,
      name: "Presidential",
    slug: "presidential-room",
    type: "presidential",
    price: 5500,
    size: 8000,
    capacity: 8,
    pets: true,
    breakfast: true,
    featured: false,
    intro: "Feel like a king in your kingdom",
    extras: [
      "Plush pillows and breathable bed linens",
      "Soft, oversized bath towels",
      "Full-sized, pH-balanced toiletries",
      "Complimentary refreshments",
      "Adequate safety/security",
      "Internet",
      "Comfortable beds"
    ],
    images: "https://images.pexels.com/photos/879010/pexels-photo-879010.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
  },
  {
    id: 14,
    name: "Double vintage",
    slug: "double-basic",
    type: "double",
    price: 3500,
    size: 350,
    capacity: 2,
    pets: false,
    breakfast: false,
    featured: false,
    extras: [
      "Plush pillows and breathable bed linens",
      "Soft, oversized bath towels",
      "Full-sized, pH-balanced toiletries",
      "Complimentary refreshments",
      "Adequate safety/security",
      "Internet",
      "Comfortable beds"
    ],
    images: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
  },
  {
    id: 15,
    name: "Family fun",
    slug: "double-basic",
    type: "family",
    price: 1000,
    size: 250,
    capacity: 2,
    pets: false,
    breakfast: false,
    featured: false,
    extras: [
      "Plush pillows and breathable bed linens",
      "Soft, oversized bath towels",
      "Full-sized, pH-balanced toiletries",
      "Complimentary refreshments",
      "Adequate safety/security",
      "Internet",
      "Comfortable beds"
    ],
    images: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
  },
  {
    id: 16,
    name: "Bussiness class",
    slug: "double-basic",
    type: "presidential",
    price: 5000,
    size: 250,
    capacity: 2,
    pets: false,
    breakfast: false,
    featured: false,
    extras: [
      "Plush pillows and breathable bed linens",
      "Soft, oversized bath towels",
      "Full-sized, pH-balanced toiletries",
      "Complimentary refreshments",
      "Adequate safety/security",
      "Internet",
      "Comfortable beds"
    ],
    images: "https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
  }

]